runnerTag: latest
authCompartmentOcid: ocid1.compartment.oc1..aaaaaaaaykdfnwdgzksazqom3cujcofsx2o7mrxlrsnsnokp3z6yrijrtgna
phoneBookId: oracle-kubernetes-engine
name: release-validator-ccm-csi
team: OKE Nodes and Apps
description: OKE Nodes and Apps Image Release Validator
majorversion: 0
minorversion: 1
shortversion: ${majorversion}.${minorversion}
version: ${BLD_SHORT_COMMIT_HASH}_${BLD_NUMBER}
releaseBranches: ["internal", "pull-requests", "OKE-32428"]
triggerOnCommitBranches:  ["internal", "pull-requests"]

initialBuildNumber: {
  "master" : 1
}

steps:
  [
    {
      name: create_pop
      type: make
      makeCommands: [
        { target: "build" }
      ]
      artifacts: [ "**" ]
      environment: {
        "VERSION":${version}
      }
    },
    {
      name: push_pop
      type: publishgeneric
      dependsOn: create_pop
      repository: odo-artifacts-signed-generic-local
      filePathsToPublish: [ {
        localFile: "out/*"
      } ]
    }
  ]
