FROM --platform=linux/arm64 odo-docker-signed-local.artifactory.oci.oraclecorp.com/oke/go-boringcrypto-4493-aarch64:1.21.5-243 as builder

ARG COMPONENT
ENV SRC /gopath/src/github.com/oracle/oci-cloud-controller-manager

RUN yum-config-manager --disable \* && yum-config-manager --add-repo https://artifactory.oci.oraclecorp.com/io-ol8-latest-yum-aarch64-local && yum repolist enabled \
  && yum install -y make \
  && yum clean all


RUN mkdir -p /go/bin $SRC
ADD . $SRC

WORKDIR $SRC

RUN ARCH=arm64 COMPONENT=${COMPONENT} make clean build-arm

FROM --platform=linux/arm64 ocr-docker-remote.artifactory.oci.oraclecorp.com/os/oraclelinux:8-slim-fips as base

RUN rm -f /etc/yum.repos.d/*
COPY artifactory_arm.repo /etc/yum.repos.d/.

RUN microdnf install -y io-ol8-container-hardening && \
    microdnf -y install util-linux e2fsprogs xfsprogs && \
    microdnf update && \
    microdnf clean all && \
    rm -rf /var/cache/yum /var/lib/yum/* /var/lib/rpm/* /var/cache/yum/* /var/tmp/* /root/.gem /usr/share/doc/*

FROM scratch
COPY --from=base / /

COPY scripts/* /sbin/

RUN chmod 755 /sbin/encrypt-mount && \
    chmod 755 /sbin/encrypt-umount && \
    chmod 755 /sbin/rpm-host && \
    chmod 755 /sbin/chroot-bash

COPY --from=0 /gopath/src/github.com/oracle/oci-cloud-controller-manager/dist/* /usr/local/bin/
