# To use the OCI Build Service you place a file name ocibuild.conf at the root of your git repo.
# This file, written using the HOCON syntax, will cause a build to automatically be triggered when commits are pushed to your repo.
# The ocibuild.conf file also determines how build service executes the build commands on the source code in your repo.
#
# Build Service Reference: https://confluence.oci.oraclecorp.com/x/7kMZBg
# Where is my build: https://devops.oci.oraclecorp.com/build
# HOCON reference: https://github.com/lightbend/config/blob/master/HOCON.md
# Build Service Slack: #oci_build_svc_users

# Caution, using runnerTag = latest will break the local build of ocibuild.conf,
# for local ocibuild please use the version from above mentioned Build Service Reference
runnerTag = latest
name: oci-cloud-controller-manager
team: OKE
phoneBookId: oracle-kubernetes-engine
description: oci-cloud-controller-manager build for oke
branch: ${BLD_BRANCH}
# Kubernetes Version
k8sVersion: v1.33
# !!IMP: If you are updating the k8sVersion field, the please update this field too
# It is used to correct publish paths which are compatible with node pacakges.
k8sVersionWithoutV: "1.33"
version: ${k8sVersion}-${BLD_SHORT_COMMIT_HASH}-${BLD_NUMBER}

# CCM release version
majorVersion: 1
# update minorVersion for feature releases
minorVersion: 15
# update patchVersion for bugfixes and small improvements
patchVersion: 1
ccmVersion: ${k8sVersion}-${majorVersion}.${minorVersion}.${patchVersion}

# fvd-rpm
repo: "odo-artifacts-signed-generic-local"
release: ${BLD_NUMBER}.${BLD_SHORT_COMMIT_HASH}
enableGit: true

initialBuildNumber = {
"master": 1
"internal": 1
}
releaseBranches: ["master", "internal", "release*", "oss-oci-ccm-csi/master","oss-oci-ccm-csi/main"]
triggerOnCommitBranches: ["main", "pull-requests", "master", "internal", "release*", "oss-oci-ccm-csi/master","oss-oci-ccm-csi/main"]
authCompartmentOcid: ocid1.compartment.oc1..aaaaaaaaykdfnwdgzksazqom3cujcofsx2o7mrxlrsnsnokp3z6yrijrtgna
pipelineId: ocid1.devopsbuildpipeline.oc1.phx.aaaaaaaa4gcbttfzkdvpxhnqj7j7qom7alv44lto2txra6doz5itye555fyq
bitbucketTag: {"enabled": true, "tagName": ${ccmVersion}-${BLD_NUMBER}, "description": "cloud-provider-oci version "${ccmVersion}-${BLD_NUMBER}}

steps:
  [
    {
      name: gitcheckout
      type: git
      gitCloneType: full
      cloneSubmodules: true
      artifacts: [
        "**"
      ]
    },
    {
      name: dockerize_ccm
      type: dockerizer
      dependsOn: gitcheckout
      dockerBuildPwd: "."
      dockerBuildArgs: {
        "COMPONENT": "oci-cloud-controller-manager oci-volume-provisioner oci-flexvolume-driver oci-csi-controller-driver oci-csi-node-driver",
      }
      images : [
        {
          platform: linux/amd64
           dockerFile: "./Dockerfile_internal"
        },
        {
           platform: linux/arm64
           dockerFile: "./Dockerfile_arm_internal"
        }
    ],
    artifacts: [
        "**"
      ]
    },
    {
      name: publish_public_docker_ccm
      type: publishdocker
      dependsOn: dockerize_ccm
      repository: odo-docker-signed-local
      imageName: "cloud-provider-oci" 
      skipOnDryRun: false
      artifacts: [
          "**"
      ]
    }
  ]