# To use the OCI Build Service you place a file name ocibuild.conf at the root of your git repo.
# This file, written using the HOCON syntax, will cause a build to automatically be triggered when commits are pushed to your repo.
# The ocibuild.conf file also determines how build service executes the build commands on the source code in your repo.
#
# Build Service Reference: https://confluence.oci.oraclecorp.com/x/7kMZBg
# Where is my build: https://devops.oci.oraclecorp.com/build
# HOCON reference: https://github.com/lightbend/config/blob/master/HOCON.md
# Build Service Slack: #oci_build_svc_users

# Caution, using runnerTag = latest will break the local build of ocibuild.conf,
# for local ocibuild please use the version from above mentioned Build Service Reference
runnerTag = latest
name: oci-cloud-controller-manager-e2e
team: OKE
phoneBookId: oracle-kubernetes-engine
description: oci-cloud-controller-manager e2e code for oke
majorversion: 1
minorversion: 0
shortversion: ${majorversion}.${minorversion}

variables: {
    CCM_RELEASE_VERSION_E2E: 1.30
    E2E_BRANCH: "release-1.30"
}

version: ${CCM_RELEASE_VERSION_E2E}-${BLD_SHORT_COMMIT_HASH}-${BLD_NUMBER}
initialBuildNumber = {
  "master": 1
  "internal": 1
}
releaseBranches: ["TASK/lalitsin/devops-e2e-pipeline-dont-run"]
triggerOnCommitBranches: ["TASK/lalitsin/devops-e2e-pipeline-dont-run"]
authCompartmentOcid: ocid1.compartment.oc1..aaaaaaaaykdfnwdgzksazqom3cujcofsx2o7mrxlrsnsnokp3z6yrijrtgna
pipelineId: ocid1.devopsbuildpipeline.oc1.phx.aaaaaaaa557tjac6wrkq5kalridi7etg5udyrog6ay53dwuxaqqjnql7iwta

sendNotificationBranches: ["**"]
slackChannels: [${BLD_BRANCH}]

enableGit: true

exportVariables = {
    BLD_VERSION = ${version}
    CCM_RELEASE_VERSION_E2E = ${CCM_RELEASE_VERSION_E2E}
}

steps: [
    {
        name: git-checkout
        type: git
        printVerboseLogs: false
        gitCloneType: shallow
        cloneSubmodules: true
        artifacts: [
            "**"
        ]
    },
    {
      name: checkout-e2e-branch
      type: make
      dependsOn: git-checkout
      printVerboseLogs: false
      environment: {
        "BLD_VERSION": ${version}
        "E2E_BRANCH": ${E2E_BRANCH}
      }
      compartmentOcid: ocid1.compartment.oc1..aaaaaaaagfsaxx6tfzaj4qazvhs2fousvjcbonhistjqh34vmxpkklxocxbq
      makeCommands: [
        { target: "checkout-e2e-branch-build-service" }
      ]
      secrets: [
        { envVarName: "BITBUCKET_KEY", secretServicePath: "/secret/oke-ccm-secrets-okefoundationspipelines/bb-private-key/latest"},
      ]
      artifacts: ["oci-cloud-controller-manager-"${version}".tar.gz"]
      skipOnDryRun: false
    },
  {
    name: publish_e2e_code
    type: publishgeneric
    dependsOn: checkout-e2e-branch
    printVerboseLogs: false
    repository: clusters-dev-generic-local
    filePathsToPublish : [
      {
        localFile : "oci-cloud-controller-manager-"${version}".tar.gz",
        targetDir : "/oci-cloud-controller-manager-e2e/"${CCM_RELEASE_VERSION_E2E}"/"
      }
    ]
    skipOnDryRun: false
  },
]
