# To use the OCI Build Service you place a file name ocibuild.conf at the root of your git repo.
# This file, written using the HOCON syntax, will cause a build to automatically be triggered when commits are pushed to your repo.
# The ocibuild.conf file also determines how build service executes the build commands on the source code in your repo.
#
# Build Service Reference: https://confluence.oci.oraclecorp.com/x/7kMZBg
# Where is my build: https://devops.oci.oraclecorp.com/build
# HOCON reference: https://github.com/lightbend/config/blob/master/HOCON.md
# Build Service Slack: #oci_build_svc_users

# Caution, using runnerTag = latest will break the local build of ocibuild.conf,
# for local ocibuild please use the version from above mentioned Build Service Reference
runnerTag = latest
name: oci-cloud-controller-manager-e2e
team: OKE
phoneBookId: oracle-kubernetes-engine
description: oci-cloud-controller-manager e2e code for oke
majorversion: 1
minorversion: 0
shortversion: ${majorversion}.${minorversion}
version: ${CCM_RELEASE_VERSION_E2E}-${BLD_SHORT_COMMIT_HASH}-${BLD_NUMBER}
sshKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC07ybO1OfwsfoVwEi95aelL7j3/Eiyzh28sqCeihN0HHtBTw8UrHSsl5lV7MerhUH7iH4hfY91vcby0K2tpoMl1FWjf26s6rDtzjawJA8Q2wSV3NUI0GP+r7VoH+YbxrfXXDhbDlYcBYjOIDhH5GL0/3vRL7kGnUmXV9RzWmfVbz/24u/uA/pK0GUvKWwXAXBYqDle6GtWBDngocSbEF0nc+SJBONH0oqPlCUxt1LpmxxOtBsA1UvxsTzrZIuP2Wf4vigVqAogqMc5g13G/flSE5dCXqLDacOyobrNhSc6GgAWF+ZnEEF2dX/aR5d08Zwh9xymmdPNFKftr4Jzb8UPh4Ha3NUZT7TJipKOz8uj2ezGYXx+ltfg55Kapx4tOP0xU7u07vu1favfd/pn7QKJWp3QYO2tKIZk5euIBR+5MZPQnAItfQbRXA1EvTRY39J7hmwBfeArs6LHKWeRjBri11UJX5wzM44orY23HeCb4hsF0QH7/Y3vQOon3q/OeCTJNJbwiVJwaw0SevbDRGCZkLxy0wLtoNdv4I+dEXF/Dbevv73gdsDbk7tCMk5I/nlV6q1oM9aMrvtwjsYysKrkCSCY3eu/d10sAfbzJzaf1htUj07OkHEgRaG3oQ3+Rn+MgEyIsOPJjeoYiHZRSZbf+F8Y/qboBKvcPQ63evbRKQ== e2e_user@oracle.com"
initialBuildNumber = {
  "master": 1
  "internal": 1
}
releaseBranches: ["master", "release*", "internal"]
triggerOnCommitBranches: []
authCompartmentOcid: ocid1.compartment.oc1..aaaaaaaaykdfnwdgzksazqom3cujcofsx2o7mrxlrsnsnokp3z6yrijrtgna
pipelineId: ocid1.devopsbuildpipeline.oc1.phx.aaaaaaaa557tjac6wrkq5kalridi7etg5udyrog6ay53dwuxaqqjnql7iwta

sendNotificationBranches: ["*"]
slackChannels: ["#oke-ccm-csi-builds"]

enableGit: true

exportVariables = {
    BLD_VERSION = ${version}
    BLD_SSH_KEY = ${sshKey}
}

steps: [
    {
      name: checkout-e2e-branch
      type: make
      environment: {
        "BUILD_NUMBER": ${BLD_NUMBER}
        "E2E_BRANCH": ${E2E_BRANCH}
      }
      makeCommands: [
        { target: "checkout-e2e-branch-build-service" }
      ]
      artifacts: ["**"]
    },
  {
    name: publish_e2e_code
    type: publishgeneric
    dependsOn: checkout-e2e-branch
    repository: clusters-dev-generic-local
    filePathsToPublish : [
      {
        localFile : ".",
        targetDir : "/oci-cloud-controller-manager-e2e/"${version}"/"
      }
    ]
    skipOnDryRun: false
  },
]
