#!/bin/bash

set -x -v

env_file=$(mktemp)
unset OCI_RESOURCE_PRINCIPAL_PRIVATE_PEM
# env | grep -v XDG_SESSION_ID | grep -v TEAMCITY_BUILD_PROPERTIES_FILE | grep -v TMPDIR | grep -v JDK_18_x64 | grep -v TEAMCITY_CAPTURE_ENV | grep -v "^USER" | grep -v TEMP | grep -v JDK_18 | grep -v JRE_HOME | grep -v PATH | grep -v PWD | grep -v JAVA_HOME | grep -v LANG | grep -v SHLVL | grep -v HOME | grep -v JDK_HOME | grep -v XDG_RUNTIME_DIR > "$env_file"

$(cat "${env_file}")

#touch "${env_file}"
#env > "${env_file}"
#env
#cat "${env_file}"

>.env_file
for var in $(compgen -v | grep -Ev '^(BASH)'); do
    var_fixed=$(printf "%s" "${!var}" | tr -d '\n' )
    echo "$var=${var_fixed}" >>.env_file
done

$(cat .env_file)

export E2E_TEST_BASE_IMAGE=${E2E_TEST_BASE_IMAGE//artifactory.oci.oraclecorp.com/pipelines.artifactory.us-phoenix-1.oci.oracleiaas.com}

docker --config "$DOCKER_CONFIG_DIR" run \
	--volumes-from "${DIND_NAME}" \
	-e LOCAL_RUN="${LOCAL_RUN:-0}" \
	-e PATH="/usr/local/go/bin:/gopath/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/usr/local/oci/bin" \
	-e GOPATH="/gopath" \
	-e http_proxy="${HTTP_PROXY}" \
	-e https_proxy="${HTTPS_PROXY}" \
	-e no_proxy="${NO_PROXY}" \
	-e ADD_OKE_SYSTEM_TAGS="${ADD_OKE_SYSTEM_TAGS}" \
	-e ADLOCATION="${ADLOCATION}" \
	-e ARCHITECTURE_AMD="${ARCHITECTURE_AMD}" \
	-e ARCHITECTURE_ARM="${ARCHITECTURE_ARM}" \
	-e BACKEND_NSG_OCIDS="${BACKEND_NSG_OCIDS}" \
	-e BB_KEY="${BB_KEY}" \
	-e BLD_BRANCH="${BLD_BRANCH}" \
	-e BLD_BRANCH_SUFFIX="${BLD_BRANCH_SUFFIX}" \
	-e BLD_BRANCH_SUFFIX_LC="${BLD_BRANCH_SUFFIX_LC}" \
	-e BLD_COMMIT_HASH="${BLD_COMMIT_HASH}" \
	-e BLD_DATE="${BLD_DATE}" \
	-e BLD_DATE_TIME="${BLD_DATE_TIME}" \
	-e BLD_GUID="${BLD_GUID}" \
	-e BLD_INPUT_DIR="${BLD_INPUT_DIR}" \
	-e BLD_NAME="${BLD_NAME}" \
	-e BLD_NON_RELEASE_SUFFIX="${BLD_NON_RELEASE_SUFFIX}" \
	-e BLD_NON_RELEASE_SUFFIX_LC="${BLD_NON_RELEASE_SUFFIX_LC}" \
	-e BLD_NUMBER="${BLD_NUMBER}" \
	-e BLD_OUTPUT_DIR="${BLD_OUTPUT_DIR}" \
	-e BLD_REF_SPEC="${BLD_REF_SPEC}" \
	-e BLD_REF_SPEC_SUFFIX="${BLD_REF_SPEC_SUFFIX}" \
	-e BLD_RUNTIME_ATTRIBUTES="${BLD_RUNTIME_ATTRIBUTES}" \
	-e BLD_SHORT_COMMIT_HASH="${BLD_SHORT_COMMIT_HASH}" \
	-e BLD_SNAPSHOT_SUFFIX="${BLD_SNAPSHOT_SUFFIX}" \
	-e BLD_VERSION="${BLD_VERSION}" \
	-e BLD_VSC_ROOT="${BLD_VSC_ROOT}" \
	-e CCM_RELEASE_VERSION_E2E="${CCM_RELEASE_VERSION_E2E}" \
	-e CLUSTER_TYPE="${CLUSTER_TYPE}" \
	-e CMEK_KMS_KEY="${CMEK_KMS_KEY}" \
	-e CNI_TYPE="${CNI_TYPE}" \
	-e COMPARTMENT="${COMPARTMENT}" \
	-e COMP_WORDBREAKS="${COMP_WORDBREAKS}" \
	-e CREATE_NPN_CLUSTER="${CREATE_NPN_CLUSTER}" \
	-e CREATE_UHP_NODEPOOL="${CREATE_UHP_NODEPOOL}" \
	-e CREATE_VCN_NATIVE_CLUSTER="${CREATE_VCN_NATIVE_CLUSTER}" \
	-e DELEGATION_GROUP_ID="${DELEGATION_GROUP_ID}" \
	-e DELETE_NAMESPACE="${DELETE_NAMESPACE}" \
	-e DIND_NAME="${DIND_NAME}" \
	-e DOCKER_CONFIG_DIR="${DOCKER_CONFIG_DIR}" \
	-e D_BUILD_STATUS="${D_BUILD_STATUS}" \
	-e E2E_BRANCH="${E2E_BRANCH}" \
	-e E2E_NODE_COUNT="${E2E_NODE_COUNT}" \
	-e E2E_TEST_BASE_IMAGE="${E2E_TEST_BASE_IMAGE}" \
	-e ENABLE_CREATE_CLUSTER="${ENABLE_CREATE_CLUSTER}" \
	-e ENABLE_PARALLEL_RUN="${ENABLE_PARALLEL_RUN}" \
	-e EUID="${EUID}" \
	-e EXISTING_CLUSTER_OCID="${EXISTING_CLUSTER_OCID}" \
	-e FILES="${FILES}" \
	-e FOCUS="${FOCUS}" \
	-e FOCUS_SKIP="${FOCUS_SKIP}" \
	-e FSS_VOLUME_HANDLE="${FSS_VOLUME_HANDLE}" \
	-e FSS_VOLUME_HANDLE_ARM="${FSS_VOLUME_HANDLE_ARM}" \
	-e GO_IMAGE="${GO_IMAGE}" \
	-e IMAGE_PULL_REPO="${IMAGE_PULL_REPO}" \
	-e KAR_VERSION="${KAR_VERSION}" \
	-e KUBECONFIG="${KUBECONFIG}" \
	-e KUBECTL="${KUBECTL}" \
	-e LBRGNSUBNET="${LBRGNSUBNET}" \
	-e LBRGNSUBNET_AMD="${LBRGNSUBNET_AMD}" \
	-e LBRGNSUBNET_ARM="${LBRGNSUBNET_ARM}" \
	-e LBSUBNET1="${LBSUBNET1}" \
	-e LBSUBNET2="${LBSUBNET2}" \
	-e LOCAL_RUN="${LOCAL_RUN}" \
	-e MNT_TARGET_COMPARTMENT_ID="${MNT_TARGET_COMPARTMENT_ID}" \
	-e MNT_TARGET_ID="${MNT_TARGET_ID}" \
	-e MNT_TARGET_SUBNET_ID="${MNT_TARGET_SUBNET_ID}" \
	-e NODE_SHAPE_AMD="${NODE_SHAPE_AMD}" \
	-e NODE_SHAPE_ARM="${NODE_SHAPE_ARM}" \
	-e NSG_OCIDS_AMD="${NSG_OCIDS_AMD}" \
	-e NSG_OCIDS_ARM="${NSG_OCIDS_ARM}" \
	-e OCI_ARTIFACTS_DIR="${OCI_ARTIFACTS_DIR}" \
	-e OCI_FINGERPRINT="${OCI_FINGERPRINT}" \
	-e OCI_K8SSUBNET="${OCI_K8SSUBNET}" \
	-e OCI_KEY="${OCI_KEY}" \
	-e OCI_LBRGNSUBNET="${OCI_LBRGNSUBNET}" \
	-e OCI_NODESUBNET_AMD="${OCI_NODESUBNET_AMD}" \
	-e OCI_NODESUBNET_ARM="${OCI_NODESUBNET_ARM}" \
	-e OCI_PIPELINE_ID="${OCI_PIPELINE_ID}" \
	-e OCI_PIPELINE_RUN_ID="${OCI_PIPELINE_RUN_ID}" \
	-e OCI_PIPELINE_RUN_NUMBER="${OCI_PIPELINE_RUN_NUMBER}" \
	-e OCI_PRIMARY_SOURCE_BRANCH_NAME="${OCI_PRIMARY_SOURCE_BRANCH_NAME}" \
	-e OCI_PRIMARY_SOURCE_COMMIT_HASH="${OCI_PRIMARY_SOURCE_COMMIT_HASH}" \
	-e OCI_PRIMARY_SOURCE_NAME="${OCI_PRIMARY_SOURCE_NAME}" \
	-e OCI_PRIMARY_SOURCE_URL="${OCI_PRIMARY_SOURCE_URL}" \
	-e OCI_REGION="${OCI_REGION}" \
	-e OCI_RESOURCE_PRINCIPAL_NAME="${OCI_RESOURCE_PRINCIPAL_NAME}" \
	-e OCI_RESOURCE_PRINCIPAL_REGION="${OCI_RESOURCE_PRINCIPAL_REGION}" \
	-e OCI_RESOURCE_PRINCIPAL_RPST="${OCI_RESOURCE_PRINCIPAL_RPST}" \
	-e OCI_RESOURCE_PRINCIPAL_VERSION="${OCI_RESOURCE_PRINCIPAL_VERSION}" \
	-e OCI_RGNSUBNET="${OCI_RGNSUBNET}" \
	-e OCI_STAGE_ID="${OCI_STAGE_ID}" \
	-e OCI_SUBNET1="${OCI_SUBNET1}" \
	-e OCI_SUBNET2="${OCI_SUBNET2}" \
	-e OCI_SUBNET3="${OCI_SUBNET3}" \
	-e OCI_TENANCY="${OCI_TENANCY}" \
	-e OCI_TEST_ID="${OCI_TEST_ID}" \
	-e OCI_TEST_STAGE_NAME="${OCI_TEST_STAGE_NAME}" \
	-e OCI_TSS_AGENT_VERSION="${OCI_TSS_AGENT_VERSION}" \
	-e OCI_USER="${OCI_USER}" \
	-e OCI_WORKSPACE_DIR="${OCI_WORKSPACE_DIR}" \
	-e OKE_CLUSTER_K8S_VERSION_INDEX="${OKE_CLUSTER_K8S_VERSION_INDEX}" \
	-e OKE_CLUSTER_K8S_VERSION_INDEX_UPGRADE_TO="${OKE_CLUSTER_K8S_VERSION_INDEX_UPGRADE_TO}" \
	-e OKE_ENDPOINT_AMD="${OKE_ENDPOINT_AMD}" \
	-e OKE_ENDPOINT_ARM="${OKE_ENDPOINT_ARM}" \
	-e OKE_NODEPOOL_K8S_VERSION_INDEX="${OKE_NODEPOOL_K8S_VERSION_INDEX}" \
	-e OKE_NODEPOOL_K8S_VERSION_INDEX_UPGRADE_TO="${OKE_NODEPOOL_K8S_VERSION_INDEX_UPGRADE_TO}" \
	-e OKE_WAIT_TIME="${OKE_WAIT_TIME}" \
	-e PARENT_IMAGE_PREFIX="${PARENT_IMAGE_PREFIX}" \
	-e PBIDS_INTEG_TEST_ENABLED="${PBIDS_INTEG_TEST_ENABLED}" \
	-e POD_SUBNET="${POD_SUBNET}" \
	-e POD_SUBNET_AMD="${POD_SUBNET_AMD}" \
	-e POLICY_OCID="${POLICY_OCID}" \
	-e POST_UPGRADE="${POST_UPGRADE}" \
	-e PROXYMUX_VERSION="${PROXYMUX_VERSION}" \
	-e PUB_SSHKEY="${PUB_SSHKEY}" \
	-e REGION_SECRETS="${REGION_SECRETS}" \
	-e RESERVED_IP="${RESERVED_IP}" \
	-e SCOPE="${SCOPE}" \
	-e SECONDARY_CONTAINER_LIMIT="${SECONDARY_CONTAINER_LIMIT}" \
	-e SECONDS="${SECONDS}" \
	-e SECRETS_CHECKOUT_PATH="${SECRETS_CHECKOUT_PATH}" \
	-e SECRETS_LOCAL="${SECRETS_LOCAL}" \
	-e SKIP_CLUSTER_DELETION="${SKIP_CLUSTER_DELETION}" \
	-e SKIP_PRE_BAKED_IMAGE="${SKIP_PRE_BAKED_IMAGE}" \
	-e SOPS_OCI_KEY="${SOPS_OCI_KEY}" \
	-e SSV2HELM_VERSION="${SSV2HELM_VERSION}" \
	-e STATIC_SNAPSHOT_COMPARTMENT_ID="${STATIC_SNAPSHOT_COMPARTMENT_ID}" \
	-e TENANCY="${TENANCY}" \
	-e TERM="${TERM}" \
	-e TMPDIR="${TMPDIR}" \
	-e TM_ID="${TM_ID}" \
	-e UID="${UID}" \
	-e USER="${USER}" \
	-e USE_REGIONALSUBNET="${USE_REGIONALSUBNET}" \
	-e V2SUBNETID="${V2SUBNETID}" \
	-e VCN="${VCN}" \
	-e VCN_AMD="${VCN_AMD}" \
	-e VCN_ARM="${VCN_ARM}" \
    -e workspaceDirectory="${workspaceDirectory}" \
	--net=host \
	-v "$(pwd)":/gopath/src/github.com/oracle/oci-cloud-controller-manager  \
	-w /gopath/src/github.com/oracle/oci-cloud-controller-manager  \
	-v "$(pwd)/config":/config \
	-v "$(pwd)/secrets":/secrets \
	"${E2E_TEST_BASE_IMAGE:-odo-docker-signed-local.pipelines.artifactory.us-phoenix-1.oci.oracleiaas.com/odx-oke/oke/k8-manager-base:ginkgo-1.0.9}" \
	/bin/bash -c "ls -ltr && yum-config-manager --add-repo=https://pipelines.artifactory.us-phoenix-1.oci.oracleiaas.com/io-ol7-latest-yum-local && yum install -yy openssl && make \"$1\""
