#!/bin/bash

# ==============================================================================
# Script: validate.sh
# Purpose: Post-task validation of Go code generated by the AI agent.
# ==============================================================================

echo "Verifying compilation (go build)..."
if ! go build -mod=vendor ./cmd/oci-cloud-controller-manager; then
    echo "❌ Validation Error: 'go build' failed. The code does not compile."
    # The agent will read the standard error output from 'go build' to see the exact line numbers
    exit 1
fi
