apiVersion: v1
data:
  oci-lustre-client-setup: |-
    #!/bin/bash
    set -o errexit
    set -o pipefail
    set -o nounset
    
    LUSTRE_VERSION=2.15.3
    LUSTRE_PACKAGE_VERSION="${LUSTRE_VERSION}-1"
    LUSTRE_PACKAGES_OBJECT_STORE_URL=https://objectstorage.us-saltlake-2.oraclecloud.com/p/jcApbLrU34xHOdv-zVT34suRXCwvJswskv4gMIMTyE6Y2ExOshZ7NN_3k3h--u96/n/axsbohthbgkv/b/lustre-images/o/deb/${LUSTRE_VERSION}_dkms/client_base/
    LUSTRE_PKG_DIR="/tmp/lustre-${LUSTRE_PACKAGE_VERSION}-packages"
    
    pkgs=(
        "lustre-client-modules-dkms_${LUSTRE_PACKAGE_VERSION}_amd64.deb"
        "lustre-client-utils_${LUSTRE_PACKAGE_VERSION}_amd64.deb"
    )
    
    # Log function for consistent logging
    log() {
        echo "$(date -u +"%Y-%m-%dT%H:%M:%S.%3NZ") - $1"
    }
    export SYSTEMCTL_FORCE_BUS=1

    # Remove Lustre modules, wait for some time for the modules to be removed
    retry=0
    while which lustre_rmmod  && ! lustre_rmmod && [ $retry -lt 10 ]
    do
        log "Failed to unload Lustre modules, retry=$retry"
        sleep 30
        retry=$((retry+1))
    done

    if [ $retry -eq 10 ]; then
        log "Failed to unload Lustre modules after 5 minutes, this node likely require a reboot"
        exit 1
    fi
    log "Successfully unloaded Lustre modules, proceeding with Lustre client installation/upgrade"

    log "Removing existing lustre packages"
    apt-get remove --purge -y lustre-client-modules-dkms || true
    apt-get remove --purge -y lustre-client-utils || true
    #pre requisite for building lustre packages
    log "Installing linux headers"
    dpkg --configure -a
    apt-get update
    apt-get install -y --no-upgrade linux-headers-oracle
    
    # Array to hold packages that are not installed
    not_installed_pkgs=()
    
    # Loop over the packages
    for package in "${pkgs[@]}"; do
        log "Checking $package installation on system."
        package_to_query="${package//_${LUSTRE_PACKAGE_VERSION}_amd64.deb/}"
        set +o errexit
        if dpkg -s "$package_to_query" | grep "install ok installed" &> /dev/null; then
            log "Package $package is already installed."
        else
            log "Package $package is not currently installed."
            not_installed_pkgs+=("$package")
        fi
        set -o errexit
    done
    
    # If there are any packages not installed
    if [ ${#not_installed_pkgs[@]} -ne 0 ]; then
        mkdir -p $LUSTRE_PKG_DIR
        cd $LUSTRE_PKG_DIR
        pwd
        log "Downloading and installing missing packages..."
        if ! printf '%s\n' "${not_installed_pkgs[@]}" | xargs -I{} -P8 curl -O "${LUSTRE_PACKAGES_OBJECT_STORE_URL}{}"; then
            log "Failed to download one or more packages."
            exit 1
        fi
    
        if ! (apt-get update && apt-get install -y ./*.deb && rm -f ./*.deb) then
            log "Failed to install one or more packages."
            exit 1
        fi
        log "Packages installed successfully."
    else
        log "All required packages are already installed."
    fi
    # Try to load kernel module, to verify kernel module
    if ! (modprobe lnet) then
    log "Failed to load kernel module"
    exit 1
    fi
kind: ConfigMap
metadata:
  name: oci-lustre-csi
  namespace: kube-system
