//go:build !ignore_autogenerated

/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CreateVnicDetails) DeepCopyInto(out *CreateVnicDetails) {
	*out = *in
	if in.DefinedTags != nil {
		in, out := &in.DefinedTags, &out.DefinedTags
		*out = make(map[string]map[string]string, len(*in))
		for key, val := range *in {
			var outVal map[string]string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make(map[string]string, len(*in))
				for key, val := range *in {
					(*out)[key] = val
				}
			}
			(*out)[key] = outVal
		}
	}
	if in.Ipv6AddressIpv6SubnetCidrPairDetails != nil {
		in, out := &in.Ipv6AddressIpv6SubnetCidrPairDetails, &out.Ipv6AddressIpv6SubnetCidrPairDetails
		*out = make([]Ipv6AddressIpv6SubnetCidrPairDetail, len(*in))
		copy(*out, *in)
	}
	if in.NsgIds != nil {
		in, out := &in.NsgIds, &out.NsgIds
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SecurityAttributes != nil {
		in, out := &in.SecurityAttributes, &out.SecurityAttributes
		*out = make(map[string]v1.JSON, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.ApplicationResources != nil {
		in, out := &in.ApplicationResources, &out.ApplicationResources
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.FreeformTags != nil {
		in, out := &in.FreeformTags, &out.FreeformTags
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.IpFamilies != nil {
		in, out := &in.IpFamilies, &out.IpFamilies
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CreateVnicDetails.
func (in *CreateVnicDetails) DeepCopy() *CreateVnicDetails {
	if in == nil {
		return nil
	}
	out := new(CreateVnicDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostAddress) DeepCopyInto(out *HostAddress) {
	*out = *in
	if in.V4 != nil {
		in, out := &in.V4, &out.V4
		*out = new(string)
		**out = **in
	}
	if in.V6 != nil {
		in, out := &in.V6, &out.V6
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostAddress.
func (in *HostAddress) DeepCopy() *HostAddress {
	if in == nil {
		return nil
	}
	out := new(HostAddress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Ipv6AddressIpv6SubnetCidrPairDetail) DeepCopyInto(out *Ipv6AddressIpv6SubnetCidrPairDetail) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Ipv6AddressIpv6SubnetCidrPairDetail.
func (in *Ipv6AddressIpv6SubnetCidrPairDetail) DeepCopy() *Ipv6AddressIpv6SubnetCidrPairDetail {
	if in == nil {
		return nil
	}
	out := new(Ipv6AddressIpv6SubnetCidrPairDetail)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NativePodNetwork) DeepCopyInto(out *NativePodNetwork) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NativePodNetwork.
func (in *NativePodNetwork) DeepCopy() *NativePodNetwork {
	if in == nil {
		return nil
	}
	out := new(NativePodNetwork)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NativePodNetwork) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NativePodNetworkList) DeepCopyInto(out *NativePodNetworkList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NativePodNetwork, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NativePodNetworkList.
func (in *NativePodNetworkList) DeepCopy() *NativePodNetworkList {
	if in == nil {
		return nil
	}
	out := new(NativePodNetworkList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NativePodNetworkList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NativePodNetworkSpec) DeepCopyInto(out *NativePodNetworkSpec) {
	*out = *in
	if in.MaxPodCount != nil {
		in, out := &in.MaxPodCount, &out.MaxPodCount
		*out = new(int)
		**out = **in
	}
	if in.PodSubnetIds != nil {
		in, out := &in.PodSubnetIds, &out.PodSubnetIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Id != nil {
		in, out := &in.Id, &out.Id
		*out = new(string)
		**out = **in
	}
	if in.NetworkSecurityGroupIds != nil {
		in, out := &in.NetworkSecurityGroupIds, &out.NetworkSecurityGroupIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.IPFamilies != nil {
		in, out := &in.IPFamilies, &out.IPFamilies
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.SecondaryVnics != nil {
		in, out := &in.SecondaryVnics, &out.SecondaryVnics
		*out = make([]SecondaryVnic, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NativePodNetworkSpec.
func (in *NativePodNetworkSpec) DeepCopy() *NativePodNetworkSpec {
	if in == nil {
		return nil
	}
	out := new(NativePodNetworkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NativePodNetworkStatus) DeepCopyInto(out *NativePodNetworkStatus) {
	*out = *in
	if in.State != nil {
		in, out := &in.State, &out.State
		*out = new(string)
		**out = **in
	}
	if in.Reason != nil {
		in, out := &in.Reason, &out.Reason
		*out = new(string)
		**out = **in
	}
	if in.VNICs != nil {
		in, out := &in.VNICs, &out.VNICs
		*out = make([]VNICAddress, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NativePodNetworkStatus.
func (in *NativePodNetworkStatus) DeepCopy() *NativePodNetworkStatus {
	if in == nil {
		return nil
	}
	out := new(NativePodNetworkStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NicConfiguration) DeepCopyInto(out *NicConfiguration) {
	*out = *in
	if in.IpCount != nil {
		in, out := &in.IpCount, &out.IpCount
		*out = new(int)
		**out = **in
	}
	if in.IpFamilies != nil {
		in, out := &in.IpFamilies, &out.IpFamilies
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SubnetId != nil {
		in, out := &in.SubnetId, &out.SubnetId
		*out = new(string)
		**out = **in
	}
	if in.NetworkSecurityGroupIDs != nil {
		in, out := &in.NetworkSecurityGroupIDs, &out.NetworkSecurityGroupIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ApplicationResources != nil {
		in, out := &in.ApplicationResources, &out.ApplicationResources
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NicConfiguration.
func (in *NicConfiguration) DeepCopy() *NicConfiguration {
	if in == nil {
		return nil
	}
	out := new(NicConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodAddress) DeepCopyInto(out *PodAddress) {
	*out = *in
	if in.V4 != nil {
		in, out := &in.V4, &out.V4
		*out = new(string)
		**out = **in
	}
	if in.V6 != nil {
		in, out := &in.V6, &out.V6
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodAddress.
func (in *PodAddress) DeepCopy() *PodAddress {
	if in == nil {
		return nil
	}
	out := new(PodAddress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RouterIP) DeepCopyInto(out *RouterIP) {
	*out = *in
	if in.V4 != nil {
		in, out := &in.V4, &out.V4
		*out = new(string)
		**out = **in
	}
	if in.V6 != nil {
		in, out := &in.V6, &out.V6
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RouterIP.
func (in *RouterIP) DeepCopy() *RouterIP {
	if in == nil {
		return nil
	}
	out := new(RouterIP)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecondaryVnic) DeepCopyInto(out *SecondaryVnic) {
	*out = *in
	in.CreateVnicDetails.DeepCopyInto(&out.CreateVnicDetails)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecondaryVnic.
func (in *SecondaryVnic) DeepCopy() *SecondaryVnic {
	if in == nil {
		return nil
	}
	out := new(SecondaryVnic)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubnetCidr) DeepCopyInto(out *SubnetCidr) {
	*out = *in
	if in.V4 != nil {
		in, out := &in.V4, &out.V4
		*out = new(string)
		**out = **in
	}
	if in.V6 != nil {
		in, out := &in.V6, &out.V6
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubnetCidr.
func (in *SubnetCidr) DeepCopy() *SubnetCidr {
	if in == nil {
		return nil
	}
	out := new(SubnetCidr)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VNICAddress) DeepCopyInto(out *VNICAddress) {
	*out = *in
	if in.VNICID != nil {
		in, out := &in.VNICID, &out.VNICID
		*out = new(string)
		**out = **in
	}
	if in.MACAddress != nil {
		in, out := &in.MACAddress, &out.MACAddress
		*out = new(string)
		**out = **in
	}
	if in.RouterIP != nil {
		in, out := &in.RouterIP, &out.RouterIP
		*out = new(string)
		**out = **in
	}
	if in.RouterIPs != nil {
		in, out := &in.RouterIPs, &out.RouterIPs
		*out = make([]RouterIP, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Addresses != nil {
		in, out := &in.Addresses, &out.Addresses
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.PodAddresses != nil {
		in, out := &in.PodAddresses, &out.PodAddresses
		*out = make([]PodAddress, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SubnetCidr != nil {
		in, out := &in.SubnetCidr, &out.SubnetCidr
		*out = new(string)
		**out = **in
	}
	if in.SubnetCidrs != nil {
		in, out := &in.SubnetCidrs, &out.SubnetCidrs
		*out = make([]SubnetCidr, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.HostAddress != nil {
		in, out := &in.HostAddress, &out.HostAddress
		*out = new(string)
		**out = **in
	}
	if in.HostAddresses != nil {
		in, out := &in.HostAddresses, &out.HostAddresses
		*out = make([]HostAddress, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NicConfiguration != nil {
		in, out := &in.NicConfiguration, &out.NicConfiguration
		*out = new(NicConfiguration)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VNICAddress.
func (in *VNICAddress) DeepCopy() *VNICAddress {
	if in == nil {
		return nil
	}
	out := new(VNICAddress)
	in.DeepCopyInto(out)
	return out
}
